#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
#! tap-install-registry-dockerconfig  exported from tap-operator ns using secretexports.secretgen.carvel.dev
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-install-registry-dockerconfig
spec:
  fromNamespace: tap-operator
