#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
#@ def is_equal(property, v):
#@  return hasattr(data.values, property) and ( data.values[property] == v)
#@ end
#@ if is_equal('env', 'int'):
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: micropets-cosign-keypair
spec:
  fromNamespace: cosign-system
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: micropets-other-cosign-keypair
spec:
  fromNamespace: cosign-system
---
#@ else:
---
apiVersion: v1
kind: Secret
metadata:
  name: micropets-cosign-keypair
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: micropets-other-cosign-keypair
type: Opaque
---
#@ end
