#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: micropets-cosign-keypair
spec:
  fromNamespace: cosign-system
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: micropets-other-cosign-keypair
spec:
  fromNamespace: cosign-system
---
