# Need by ClusterIssuer clusters/aks-eu-tap-6/cluster-config/config-post-install/certificats/tap-gui-letsencrypt.yaml
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: install-registry-dockerconfig
spec:
  fromNamespace: tap-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
imagePullSecrets:
  - name: install-registry-dockerconfig
