#@ load("@ytt:data", "data")
---
tap_install:
  package_repository:
    oci_repository: akseutap8registry.azurecr.io/tanzu-application-platform/tap-packages
  version:
    package_repo_bundle_tag: #@ data.values.tap_version
    package_version: #@ data.values.tap_version 
