apiVersion: v1
kind: Namespace
metadata:
  labels:
    apps.tanzu.vmware.com/tap-ns: ""
    tap.tanzu.vmware.com/languages: java_golang_angular_nodejs
    tap.tanzu.vmware.com/databases: postgres
  name: musicstore-dev
