apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: micropets-global-policy
spec:
  mode: enforce
  images:
    - glob: akseutap8registry.azurecr.io/tanzu-application-platform/* #! allow to pull all the TAP based images
    - glob: akseutap8registry.azurecr.io/library/tanzu-build-service/* #! allow to pull all the buildpacks
    - glob: akseutap8registry.azurecr.io/library/tanzu-supply-chain/*
    - glob: akseutap8registry.azurecr.io/packages-for-vmware-tanzu-data-services/* #! allow to pull images to create PGSQL databases
    #- glob: index.docker.io/*/* #! allow to images from docker hub (ex tekton )
    - glob: index.docker.io/zenika/alpine-chrome* #! allow to this image used by tekton pipeline in tap.
  authorities:
    - static:
        action: pass
---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: micropets-services-policy-micropets-integration
spec:
  mode: enforce #! warn or enforce by default
  images:
    - glob: akseutap8registry.azurecr.io/library/tanzu-supply-chain/*-micropets-int*
  authorities:
    - static:
        action: fail #! pass or fail
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjV05QeCnt8pb9MNkUjVLiahQdtsm
          0HfwxT44L6QGO+xwqydyA9GazpyQLjEiXVjTkJ/9rXrpZoma1nejUWVtew==
          -----END PUBLIC KEY-----
    #! - key:
    #!    secretRef:
    #!      name: micropets-keypair
    #!      namespace: micropets-dev #!secretref.namespace is invalid. If set, it should use the same namespace where the policy-controller was deployed
