apiVersion: ENC[AES256_GCM,data:oMI=,iv:U1+9iw2Tj+V1voV1zQXWWPOqUmoJL40/OIXhWTVFAvE=,tag:OZBes/JivEErvWQRYcHntQ==,type:str]
kind: ENC[AES256_GCM,data:DUPfA1ng,iv:P0Z8TtfIqc4pBEpfP5VN45QerZI5fTYLHi2JASbQ3Hk=,tag:RERIrs8U2UscT9rk/GJWGw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:THzfZ4KHi31HtNq6aKwu,iv:8dTg30vkKTTps3r5o0y4bdhu46dHGRQyN8wmbGyCn7Q=,tag:nONZOJO4e0Wf29ZaPc+ZQA==,type:str]
    namespace: ENC[AES256_GCM,data:0jQ1NDtmlLXnFbZaDLcNJg==,iv:OThn7oOEaFyPR2HXbPVProjA7Y9hExqTFSAOsAnkL9I=,tag:NUG2BaW4KqLNDJrB5nc2wQ==,type:str]
stringData:
    ClientID: ENC[AES256_GCM,data:1sq79m69IJ3yuQgQ62rZL9ZtJfjjij5ly62fYk21fcTSz4ND,iv:shmp+rpBlbv4wIVzhonAJ5opAUWlKi+Lh/j4pOnsmvk=,tag:bgpZjsV9qfTDy6sBwh4VDg==,type:str]
    ClientSecret: ENC[AES256_GCM,data:H+jD9vNsHFu86LWpo+2qgsUkOvBSRVGcMi0V6vAcXeopdQS53tHqbQ==,iv:vucCA1R8HQaIMDQkFHkA9Ydw4Ry1nvM0FjRYuBBLW2o=,tag:gtv6W39LhjeW1M6EbY7deg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sfvahczpatyd232kk396plhxxz7cuu5l8mw52zljg2cg7xqwdf0qp8k9q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S3k5emo4QkdoSEVjQW9V
            U3RLbm1RbWtNTE5DNm5Wdmhsbzc0ZXROSVhjCi8rUlBPK090djF2L25sOVRGaHM0
            WXNleFF4a09xSnVNeU9sQTlsenNYdlkKLS0tIGRmQTE3TTRnN04wMWNhaWRVTE4z
            eUZsM3FzRmhzeEdrMWc2MmYyYnp1ZVEKFYTtE3ePgraD1mwsAY33iAJaryxKguEP
            sY+AXKzqRiqQXq0SAy6FDEw5/BK0j1dy9KjtozbHYLQA/jSdu0HuMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-12T14:54:43Z"
    mac: ENC[AES256_GCM,data:9JLNJj+E0BEhXQKTwEaUOcAtHVLss8i5ZsD1oK4HId7ggHVxE3Y8AnnJZAqof7nsii5KID+M362g33Rx57ATil9qc6ZJ3LYnMcKhPd3qIW7A8ja96NfSvMF1izwFVpAPc5+Cfg1LPSrqSwvoVQAReuUn5Pp6xuXA6GQ1s5gpGFI=,iv:VhHGFa4V0uVE5FMlbiDeMaEq5S1jSEoBDK9MbyFgRH4=,tag:XAcRFfPXDzlStKdz9uFHUg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
