#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namx: sa-default-claim-app-operator-claim-class-mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-operator-claim-class-mongodb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: #@ data.values.name
