apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-sa
  namespace: tanzu-sync
  annotations:
    tanzu-sync.tanzu.vmware.com/variant: sops
    tanzu-sync.tanzu.vmware.com/version: 0.3.3+2023-11-30-104552_(1543ef5)
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: post-install
  namespace: tanzu-extras
  annotations:
    kapp.k14s.io/change-group: apps/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting apps/drivers"
    kapp.k14s.io/change-rule.1: "delete before deleting apps/drivers"
spec:
  serviceAccountName: tanzu-extras-sa
  fetch:
    - git:
        url: https://github.com/bmoussaud/tap-gitops.git
        ref: origin/main
        subPath: clusters/aks-eu-tap-8/cluster-config/config-post-install
  template:
    - sops:
        age:
          privateKeysSecretRef:
            name: tap-sync-age-identity
    - ytt: {}
  deploy:
    - kapp:
        rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
