---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: install-registry-dockerconfig
  namespace: accelerator-system
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  fromNamespace: tap-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: accelerator-system
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
imagePullSecrets:
  - name: install-registry-dockerconfig
