---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hack-tap-gui-cluster-admin
rules:
  - apiGroups:
      - "data.packaging.carvel.dev"
    resources:
      - "packages"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hack-tap-gui-cluster-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hack-tap-gui-cluster-admin
subjects:
  - kind: ServiceAccount
    name: tap-gui
    namespace: tap-gui
