---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: benoitdb-psql-secret-template
  namespace: database-instances-france
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: benoitdb-psql-reading
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch    
  - apiGroups:
      - dbforpostgresql.azure.upbound.io
    resources:
      - flexibleservers
    verbs:
      - get
      - list
      - watch
      - fetch
    resourceNames:
      - benoitdb-psql-flexible-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: benoitdb-psql-reader-to-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: benoitdb-psql-reading
subjects:
  - kind: ServiceAccount
    name: benoitdb-psql-secret-template
    namespace: database-instances-france
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: benoidb-psql-bindable
  namespace: database-instances-france
spec:
  serviceAccountName: benoitdb-psql-secret-template
  inputResources:
    - name: server
      ref:
        apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
        kind: FlexibleServer
        name: benoitdb-psql-flexible-server
    - name: creds
      ref:
        apiVersion: v1
        kind: Secret
        name: $(.server.spec.forProvider.administratorPasswordSecretRef.name)
  template:
    metadata:
      labels:
        app.kubernetes.io/component: benoidb-psql
        app.kubernetes.io/instance: $(.server.metadata.name)
        services.apps.tanzu.vmware.com/class: azure-postgres
    type: postgresql
    stringData:
      type: postgresql
      port: "5432"
      database: "benoitdb-psql-flexible-server-db"
      host: $(.server.status.atProvider.fqdn)
      username: $(.server.status.atProvider.administratorLogin)
    data:
      password: $(.creds.data.password)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: benoidb-psql-bindable
  namespace: database-instances-france
spec:
  toNamespace: musicstore-dev
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: benoidb-psql-bindable
  namespace: musicstore-dev
spec:
  fromNamespace: database-instances-france