
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aks-eu-tap-8-aks-eu-tap-8-micropets
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://aks-eu-tap-8-micropets.vault.azure.net
      serviceAccountRef:
        name: workload-identity-sa
        namespace: external-secrets

