
---
apiVersion: v1
kind: ServiceAccount
metadata:  
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: d838baeb-3747-4544-b127-b42876157f7d
    azure.workload.identity/tenant-id: b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0
  name: micropets-azure-vault
  namespace: external-secrets

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: micropets-azure-vault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://aks-eu-tap-8-micropets.vault.azure.net
      serviceAccountRef:
        name: micropets-azure-vault
        namespace: external-secrets
