---
apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-extras  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-extras-sa
  namespace: tanzu-extras
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-extras-tap-operator-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tap-operator-cluster-admin
subjects:
  - kind: ServiceAccount
    name: tanzu-extras-sa
    namespace: tanzu-extras
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-install-registry-dockerconfig
  namespace: tanzu-extras
spec:
  fromNamespace: tap-operator
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tap-sync-age-identity
  namespace: tanzu-extras
spec:
  fromNamespace: tap-operator
