---
tap_install:
  sensitive_values:
    shared: 
      image_registry:
        project_path: akseutap6registry.azurecr.io/library/tanzu-build-service
        username: 87d50e13-00aa-48a2-b6b3-91ba311b743e
        password: 2tJ8Q~p4cjicS-BpaXm3AWi8m49R19.m.jw4ZcvY
