#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: postgres-operator.sql.tanzu.vmware.com
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgr/extra"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgr/extra"
spec:
  serviceAccountName: tap-installer-sa
  packageRef:
    refName: postgres-operator.sql.tanzu.vmware.com
    versionSelection: {}
