apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tds-pkgr
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgr/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"

spec:
  fetch:
    imgpkgBundle:      
      image: #@ "{}/packages-for-vmware-tanzu-data-services/tds-packages:{}".format("akseutap6registry.azurecr.io", "1.12.1")
