#ENC[AES256_GCM,data:A8TBIqvLOITXlsn86f9XWTt98k1Bfho1v/dpcwv3fcbhErRCUgzSBbMf,iv:n/TVzk0RR22YnHTAoquNysFUg2JescwVjWftUOe1HiM=,tag:BS0V1pfbroKi+46hAc6klA==,type:comment]
tap_install:
    values:
        tap_gui:
            app_config:
                integrations:
                    github:
                        - host: ENC[AES256_GCM,data:Zse45PcXPuNGgA==,iv:2zwttGVofob4hAGWp/lc5RZ1W3RC3Zf629t10RhSzGM=,tag:beADJV6SOsN3D74p/woX6w==,type:str]
                          token: ENC[AES256_GCM,data:SH7eQYO6qZmbSh73WuF4+SGBX7amTghQE3ifqvIkSyxRN/nhyGEP3w==,iv:4y4vSsPaogHN/g35C+RyZ9QiqXcvxOKyV7d7mRFTbAI=,tag:n3uP7hbguKR0rmnqa6i09w==,type:str]
                auth:
                    allowGuestAccess: ENC[AES256_GCM,data:M43NdQ==,iv:ro/g6PtD3CkCH1aMuuI8ReZ3/CAAf5wbD7o7mPwr908=,tag:wQrIOIRJFqX5XBxa2Rvtnw==,type:bool]
                    environment: ENC[AES256_GCM,data:iINj,iv:7PPp0OPltfMPjHfwMDkifrtEbyR9WKqk6Frzu00+vYc=,tag:XBNB5lS4RVxbMWi/zswYbA==,type:str]
                    providers:
                        github:
                            tap:
                                clientId: ENC[AES256_GCM,data:5skNPTASnJdFnOXSYWkO7+0RFJk=,iv:gjP9SvaQJ1R8wc1zTveiYzRqYZjcbAbPcg/A3bEBQVI=,tag:13ffoMGq5T1Q4Tv39RpBoA==,type:str]
                                clientSecret: ENC[AES256_GCM,data:5AYuYRQYaorFCZNYUWm/T69EZYRDagS+i20LdezBa04esnd8i+gfqA==,iv:PhvSJiWDZsxer8vRm/egNCiEYg8F5mZaQ6dUVQAIOws=,tag:Snlv0vYQStdLnVHDqXludQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sfvahczpatyd232kk396plhxxz7cuu5l8mw52zljg2cg7xqwdf0qp8k9q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVFhIYlgwajNWcjl6WVZu
            VmpDWFV5TXRNTTJuL24vbjEyV3ZVV1haeVdBCktMdVFJWUZpRXZjU2hQZzdDa2lG
            eWpRVVhTS1AxbXJ5Tk5vcFd2TUVlVjQKLS0tICtxYmhDMmVjYjV3S1BTTE8xbmFt
            UjJHVlpmWWdLMzFLMzMybzRXajFBL28KmkfLeRpDvD5D2I+0QUIy712Mvl+81ZS8
            DSJRhNC8p6jQAKLVAnX3hG9vlCFgF97sJySIdqGPIM18JzVvZnAQWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T13:11:40Z"
    mac: ENC[AES256_GCM,data:+60D1+OuPi6xiFGl46MBUgs7InkBxVDF1yt0eZ+Uc4k69cq65SNhh8tYDwjxNY5QkqvwDuppEstpfAJs8dcMYc1EYeDN0Y3586MtK9cwLVO+n6NAdMUBlTVwclNYsGQDr2pcc3OhYnu8+xUQ7/0pOgSi6FwnnXTTBGPYOVRXG2c=,iv:y5xERxIaxO+E/LqNQAQOeTaLyrJJsMutPZmQfAxdQ7Q=,tag:fpE6uHslyYuYRUaD9KkjPQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
