tap_install:
  values:
    profile: full
    #! package_overlays:
    #!  - name: ootb-templates
    #!    secrets:
    #!      - name: git-writer-no-empty-commits-debug

    shared:
      ingress_domain: 1.6.1-rc.8.tanzu.moussaud.org

    ceip_policy_disclosed: true

    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - policy.apps.tanzu.vmware.com
      - image-policy-webhook.signingappliveview-connector

    ootb_templates:
      excluded_templates:
        - convention-template

    accelerator:
      ingress:
        include: true
        issuer: letsencrypt-http01-issuer

    contour:
      envoy:
        service:
          type: LoadBalancer

    supply_chain: basic

    ootb_supply_chain_basic:
      carvel_package:
        workflow_enabled: true
        name_suffix: pkg.mytanzu.xyz
      registry:
        server: akseutap6registry.azurecr.io
        repository: library/tanzu-supply-chain
      gitops:
        ssh_secret: ""
        server_address: https://github.com/
        repository_owner: bmoussaud
        repository_name: micropets-app-gitops

    tap_gui:
      metadataStoreAutoconfiguration: true
      tls:
        namespace: cert-manager
        secretName: tap-gui-cert-letsencrypt
      app_config:
        auth:
          allowGuestAccess: true
        catalog:
          locations:
            - type: url
              target: https://github.com/bmoussaud/micropets-app/blob/master/catalog-info.yaml
            - type: url
              target: https://github.com/bmoussaud/micropets-cats-golang/blob/main/catalog-component.yaml

    metadata_store:
      ns_for_export_app_cert: "*"
      app_service_type: ClusterIP

    scanning:
      metadataStore:
        url: ""

    namespace_provisioner:
      controller: true
      parameter_prefixes:
        - tap.tanzu.vmware.com
      default_parameters:
      #! https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.6/tap/namespace-provisioner-use-case4.html#update-serviceaccount-for-all-namespaces-4
        supply_chain_service_account:
          secrets:           
            - app-registry
            - git-ssh
            - registries-credentials            
          imagePullSecrets:
            - app-registry
            - tap-registry
        limits:
          default:
            cpu: 1700m
            memory: 1500Mi
          defaultRequest:
            cpu: 100m
            memory: 500Mi
      additional_sources:
        - git:
            url: https://github.com/bmoussaud/tap-gitops.git
            ref: origin/main
            subPath: clusters/aks-eu-tap-6/cluster-config/namespace-provisioner/resources
          path: _ytt_lib/namespace-provisioner-resources
