tap_install:
  package_repository:
    oci_repository: akseutap6registry.azurecr.io/tanzu-application-platform/tap-packages
  version:
    package_repo_bundle_tag: 1.6.2-rc.3
    package_version: 1.6.2-rc.3
