tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:s0PO5j3ez1pFZqB74+NaMfVVr0CJYOg69Kw3zaFAj1cIILDKQHgy729589imNgUP9hcCYWgVGZU=,iv:I1JTaSNc+ifjB3MHLG2QvjhkrvGqcdUPvp/TIgxfOpQ=,tag:i+qeu5q4iQI0jJ65aCacNw==,type:str]
                username: ENC[AES256_GCM,data:mz0XtKW2kYBsXay+MgSdcZ8V96c9v35E7SM4eTbITGvMIRA1,iv:G/8Fz2xSctbzBNAxSDcYQH6lMonL32hFP31L3awiOOg=,tag:IxCGdXFAM2555BZHRhybBQ==,type:str]
                password: ENC[AES256_GCM,data:mw+qiOvO1ftAdab/77cjHW6RTM1dz38ERIF/q8fchA2GRf7LyarVtg==,iv:8okb2paN/2GGDHlYL+5I/D5Z6TdmTR0FFck/eu1eFfo=,tag:rnSXzwxgmCCRNfUvd7WYSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sfvahczpatyd232kk396plhxxz7cuu5l8mw52zljg2cg7xqwdf0qp8k9q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZzd5Q3puTnNmaDhIQmxn
            Nm45Z2d1aGgvbWc2R2dNam5tTFVtT2ZTeVVzCit5blBVOENSYlNyZGJUdnNpb0w1
            WkNHLzNzbDcvdzRCZ3ZNUkUvU0hncGsKLS0tIEFrbDR0Ymk0VWp1aDVENk05M2pZ
            eVAyNG5mL3RlSVJWNlNHREJ3VCs5VGcKI8wFmu9fkx5MOoB19N6cRVhmYZvMSh3k
            1AbImvluaPYr22nH/vgik3H+HH2Dlc0cMvP34K0yAVbGGpoJ2j9rEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-19T14:18:13Z"
    mac: ENC[AES256_GCM,data:h8yNuW6CaezYMj4ZWSESq+DTIQ+9Z+ntf31hORwiFwS2Zva74JaGYTShumd+oNM4xuRyNLEcfRRTCPtPrMnyzTlfoQ1Tm4Du2V5mIPsr/lhXoOwePFWOjdZeu2hBejL+/AZWbc+8zssEr128h0Cr/yqiQos2e0W/r9KvOV2+n08=,iv:jslwH+m09mqKsPZJbnP6HbI0lBQKULFblFRdFZgJpzY=,tag:3oznA+9TPKT0e3b/PXKz9A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
