apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: cert-manager
  name: accelerator-cert-letsencrypt
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  commonName: accelerator.16x.tanzu.moussaud.org
  dnsNames:
    - accelerator.16x.tanzu.moussaud.org
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
  secretName: accelerator-cert-tls
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: accelerator-cert-tls
  namespace: tap-install
spec:
  delegations:
    - secretName: accelerator-cert-tls
      targetNamespaces:
      - accelerator-system
  

