---
apiVersion: v1
kind: Secret
metadata:
  name: accelerator-cert-tls
  namespace: cert-manager
type: kubernetes.io/tls
# Normally, we'd create an empty destination secret, but secrets of type
# 'kubernetes.io/tls' are treated in a special way and need to have properties
# data["tls.crt"] and data["tls.key"] to begin with, though they may be empty.
data:
  tls.key: ""
  tls.crt: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: cert-manager
  name: accelerator-cert-letsencrypt
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  commonName: accelerator.16x.tanzu.moussaud.org
  dnsNames:
    - accelerator.16x.tanzu.moussaud.org
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
  secretName: accelerator-cert-tls
