apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-issuer
  namespace: cert-manager
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: benoit@moussaud.org
    privateKeySecretRef:
      name: letsencrypt-http01-issuer
    solvers:
      - http01:
          ingress:
            class: contour
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: cert-manager
  name: tap-gui-cert-letsencrypt
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  commonName: tap-gui.161rc8.tanzu.moussaud.org
  dnsNames:
    -  tap-gui.161rc8.tanzu.moussaud.org
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
  secretName: tap-gui-cert-letsencrypt
