---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: install-registry-dockerconfig
  namespace: cert-manager
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  fromNamespace: tanzu-sync
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-acme-http01-solver
  namespace: cert-manager
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
imagePullSecrets:
  - name: install-registry-dockerconfig
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-issuer
  namespace: cert-manager
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tap@moussaud.org
    privateKeySecretRef:
      name: letsencrypt-http01-issuer
    solvers:
      - http01:
          ingress:
            class: contour
            podTemplate:
              spec:
                serviceAccountName: tap-acme-http01-solver
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: cert-manager
  name: tap-gui-cert-letsencrypt
  annotations:
    kapp.k14s.io/change-group: pkgi/extra
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  commonName: tap-gui.161.tanzu.moussaud.org
  dnsNames:
    - tap-gui.161.tanzu.moussaud.org
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
  secretName: tap-gui-cert-letsencrypt
