apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: drivers
  namespace: tap-operator
  annotations:
    kapp.k14s.io/change-group: apps/drivers
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi/extra"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi/extra"
spec:
  serviceAccountName: tap-sync-sa
  fetch:
    - git:
        url: https://github.com/bmoussaud/tap-gitops.git
        ref: origin/main
        subPath: clusters/aks-eu-tap-8/cluster-config/drivers
  template:
    - sops:
        age:
          privateKeysSecretRef:
            name: tap-sync-age-identity
    - ytt: {}
  deploy:
    - kapp:
        rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
