apiVersion: azure.upbound.io/v1beta1
metadata:
  name: provider-config-azure
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-secret
      key: creds
